### ISSUE TITLE
Additional Security Venues

### ISSUE THREAD

**Issue by bradreaves** [csmetrics/csmetrics.org#37]
The following are popular, high-quality venues that I recommend added to the venue list for security:

General Security conferences:
- ACM ASIACCS
- IEEE EuroS&P
- Annual Computer Security Applications Conference

More specialized venues:
- Usenix SOUPS
- ACM WiSec
- Privacy Enhancing Technologies Symposium
- Financial Cryptography and Data Security

There may be others I have not listed.

I also recommend amending the following:

- AsiaCrypt and FSE should be moved to the "cryptography" grouping. They are objectively *not* security conferences as they do not accept systems security papers.
- ACM TISSEC is now ACM TOPS. Only the name has changed, and you may want to update the listing to reflect this.

PS: Thanks for maintaining this resource!

**Comment by shinminjeong** [comment]
Hi @bradreaves, Thanks for your suggestion. 
We will consider adding the suggested venues + will update the naming in the next update.

**Comment by shinminjeong** [comment]
[SOUPS](https://dblp.uni-trier.de/db/conf/soups/), [WiSec](https://dblp.uni-trier.de/db/conf/wisec) and [PoPETs](https://dblp.uni-trier.de/db/journals/popets/) are added in 2021 update.
We could not find a conference/journal page of Financial Cryptography and Data Security from dblp.

AsiaCrypt, FSE, and TISSEC are also fixed in 2021 update! :)
See https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv
